/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACheckbox: typeof import('ant-design-vue/es')['Checkbox']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    Badge: typeof import('./src/components/Badge.vue')['default']
    CZAvatar: typeof import('./src/components/CZAvatar.vue')['default']
    Footer: typeof import('./src/components/layout/footer.vue')['default']
    Header: typeof import('./src/components/layout/header.vue')['default']
    IndexVideo: typeof import('./src/components/view/IndexVideo.vue')['default']
    MemberCard: typeof import('./src/components/MemberCard.vue')['default']
    RandomWord: typeof import('./src/components/RandomWord.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StackIcon: typeof import('./src/components/StackIcon.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    UserModal: typeof import('./src/components/UserModal/index.vue')['default']
  }
}
