/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/comment/': RouteRecordInfo<'/comment/', '/comment', Record<never, never>, Record<never, never>>,
    '/comment/[commentId]': RouteRecordInfo<'/comment/[commentId]', '/comment/:commentId', { commentId: ParamValue<true> }, { commentId: ParamValue<false> }>,
    '/comment/CommentForm': RouteRecordInfo<'/comment/CommentForm', '/comment/CommentForm', Record<never, never>, Record<never, never>>,
    '/comment/CommentItem': RouteRecordInfo<'/comment/CommentItem', '/comment/CommentItem', Record<never, never>, Record<never, never>>,
    '/comment/CommentSection': RouteRecordInfo<'/comment/CommentSection', '/comment/CommentSection', Record<never, never>, Record<never, never>>,
    '/comment/Spin': RouteRecordInfo<'/comment/Spin', '/comment/Spin', Record<never, never>, Record<never, never>>,
    '/forgotPassword': RouteRecordInfo<'/forgotPassword', '/forgotPassword', Record<never, never>, Record<never, never>>,
    '/lanqiao': RouteRecordInfo<'/lanqiao', '/lanqiao', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/member': RouteRecordInfo<'/member', '/member', Record<never, never>, Record<never, never>>,
    '/notify': RouteRecordInfo<'/notify', '/notify', Record<never, never>, Record<never, never>>,
    '/project': RouteRecordInfo<'/project', '/project', Record<never, never>, Record<never, never>>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/updateInfo': RouteRecordInfo<'/updateInfo', '/updateInfo', Record<never, never>, Record<never, never>>,
    '/winners-admin': RouteRecordInfo<'/winners-admin', '/winners-admin', Record<never, never>, Record<never, never>>,
  }
}
